
import java.awt.Component;
import javax.swing.JOptionPane;
import java.io.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sylvester-PC
 */
public class fasta extends javax.swing.JFrame {

        private Component frame;

    /**
     * Creates new form fasta
     */
    public fasta() {
        initComponents();
    }
    
                           int cl = 4 ;                   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        fasta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        amino_acidtxt = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        nuleotidetxt = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        fasta1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLaltxt = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pre Translational");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nucleotode Bases into Amino Acids");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Amino Acids into Nucelotide Bases");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("Enter Code In Fasta Format");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        fasta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fasta.setText("ENTER");
        fasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        amino_acidtxt.setColumns(20);
        amino_acidtxt.setRows(5);
        jScrollPane2.setViewportView(amino_acidtxt);

        jTabbedPane1.addTab("Amino Acids", jScrollPane2);

        nuleotidetxt.setColumns(20);
        nuleotidetxt.setRows(5);
        jScrollPane4.setViewportView(nuleotidetxt);

        jTabbedPane1.addTab("Nucleotides", jScrollPane4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setText("Enter Code In Fasta Format");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        fasta1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fasta1.setText("ENTER");
        fasta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fasta1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Amino Acid", "Nucleotide" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton3.setText("CLICK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fasta)
                                    .addComponent(jButton2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(fasta1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton5))))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(71, 71, 71))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fasta1)
                                        .addGap(97, 97, 97)
                                        .addComponent(jButton1))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(76, 76, 76))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fasta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLaltxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(13, 13, 13)))
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
     
    
    
    private void fasta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fasta1ActionPerformed
        // TODO add your handling code here:
       
        
        try
        {
           amino_acidtxt.append("AMINO ACID \n");        
          
        for (int i = 0, j=1, k=2; i < 1000; i++, j++, k++)
        {

                    if (jTextArea1.getText().charAt(i) == 'A' && jTextArea1.getText().charAt(j) == 'U' && jTextArea1.getText().charAt(k) == 'G') 
                    {
                      amino_acidtxt.setText("MET---");
                      
                      
                        for (int l = k+1, m=l+1, n=m+1; l < 1000; l=n+1, m=l+1,n=m+1)
                        {
                            if (i == cl) 
                            {
                              jTextArea1.append("\n");
                              cl =+4;
                            }
                                    if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                        amino_acidtxt.append("PHE---");
                                        cl++;
                                    }
                                    
                                    
                                    if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                        amino_acidtxt.append("PHE---");
                                    cl++;
                                    }
                                    
                                     if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                        amino_acidtxt.append("LEU---");
                                    cl++;
                                    }
                                     
                                      if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                        amino_acidtxt.append("LEU---");
                                    cl++;
                                    }
                                      
                                       if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                        amino_acidtxt.append("LEU---");
                                    cl++;
                                    }
                                       
                                        if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                        amino_acidtxt.append("LEU---");
                                    cl++;
                                    }
                                        
                                         if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                        amino_acidtxt.append("LEU---");
                                    cl++;
                                    }
                                         
                                          if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                        amino_acidtxt.append("LEU---");
                                    cl++;
                                    }
                                          
                                           if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                        amino_acidtxt.append("ISO_LEU---");
                                    cl++;
                                    }
                                           
                                            if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                        amino_acidtxt.append("ISO_LEU---");
                                    cl++;
                                    }
                                            
                                             if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                        amino_acidtxt.append("ISO_LEU---");
                                    cl++;
                                    }
                                             
                                              if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                        amino_acidtxt.append("MET---");
                                    cl++;
                                    }
                                              
                                               if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                        amino_acidtxt.append("VAL---");
                                    cl++;
                                    }
                                               
                                                if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                        amino_acidtxt.append("VAL---");
                                    cl++;
                                    }
                                                
                                                 if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                        amino_acidtxt.append("VAL---");
                                    cl++;
                                    }
                                                 
                                                  if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'U'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                        amino_acidtxt.append("VAL---");
                                    cl++;
                                    }
                                                  
                                                   if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                        amino_acidtxt.append("SER---");
                                    cl++;
                                    }
                                                   
                                                    if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                        amino_acidtxt.append("SER---");
                                    cl++;
                                    }
                                                    
                                                     if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                        amino_acidtxt.append("SER---");
                                    cl++;
                                    }
                                                     
                                                      if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                        amino_acidtxt.append("SER---");
                                    cl++;
                                    }
                                                      
                                                       if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                        amino_acidtxt.append("PRO---");
                                    cl++;
                                    }
                                                       
                                                        if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                        amino_acidtxt.append("PRO---");
                                    cl++;
                                    }
                                                        
                                                         if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                        amino_acidtxt.append("PRO---");
                                    cl++;
                                    }
                                                         
                                                          if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                        amino_acidtxt.append("PRO---");
                                    cl++;
                                    }
                                                          
                                                           if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                        amino_acidtxt.append("THR---");
                                    cl++;
                                    }
                                                           
                                                            if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                        amino_acidtxt.append("THR---");
                                    cl++;
                                    }
                                                            
                                                             if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                        amino_acidtxt.append("THR---");
                                    cl++;
                                    }
                                                             
                                                              if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                        amino_acidtxt.append("THR---");
                                    cl++;
                                    }
                                                              
                                       if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                        amino_acidtxt.append("ALA---");
                                    cl++;
                                    }
                                                               
                               if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                        amino_acidtxt.append("ALA---");
                                    cl++;
                                    }
                               
                                if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                        amino_acidtxt.append("ALA---");
                                    cl++;
                                    }
                                
                                 if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'C'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                        amino_acidtxt.append("ALA---");
                                    cl++;
                                    }
                                 
                                  if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                        amino_acidtxt.append("TYR---");
                                    cl++;
                                    }
                                  
                                   if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                    cl++;
                                    amino_acidtxt.append("TYR---");
                                    }
                                   
                                    if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                        amino_acidtxt.append("STOP---");
                                        break;
                                    }
                                    
                                     if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                        amino_acidtxt.append("STOP---");
                                        break;
                                    }
                                     
                                      if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                     cl++;
                                     amino_acidtxt.append("HIS---");
                                    }
                                      
                                       if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                     cl++;
                                     amino_acidtxt.append("HIS---");
                                    }
                                       
                                        if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                     cl++;
                                     amino_acidtxt.append("GLN---");
                                    }
                                        
                                         if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                     cl++;
                                     amino_acidtxt.append("GLN---");
                                    }
                                         
                                          if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                     cl++;
                                     amino_acidtxt.append("ASN---");
                                    }
                                          
                                           if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                        cl++;
                                        amino_acidtxt.append("ASN---");
                                    }
                                           
                                            if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                     cl++;
                                     amino_acidtxt.append("LYS---");
                                    }
                                            
                                             if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                     cl++;
                                     amino_acidtxt.append("LYS---");
                                    }
                                             
                                              if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                     cl++;
                                     amino_acidtxt.append("ASP---");
                                    }
                                              
                                               if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                     cl++;
                                     amino_acidtxt.append("ASP---");
                                    }
                                               
                                                if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                     cl++;
                                     amino_acidtxt.append("GLU---");
                                    }
                                                
                                                 if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'A'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                     cl++;
                                     amino_acidtxt.append("GLU---");
                                    }
                                                 
                                                  if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                     cl++;
                                     amino_acidtxt.append("CYC---");
                                    }
                                                  
                                                   if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                     cl++;
                                     amino_acidtxt.append("CYC---");
                                    }
                                                   
                                                    if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                        amino_acidtxt.append("STOP"); 
                                        break;
                                    }   
                                                    
                                                     if (jTextArea1.getText().charAt(l)== 'U' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                     cl++;
                                     amino_acidtxt.append("TRP---");
                                    }
                                                     
                                                      if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                     cl++;
                                     amino_acidtxt.append("ARG---");
                                    }
                                                      
                                                       if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                     cl++;
                                     amino_acidtxt.append("ARG---");
                                    }
                                                       
                                                        if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                     cl++;
                                     amino_acidtxt.append("ARG---");
                                    }
                                                        
                                                         if (jTextArea1.getText().charAt(l)== 'C' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                     cl++;
                                     amino_acidtxt.append("ARG---");
                                    }
                                                         
                                                          if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                     cl++;
                                     amino_acidtxt.append("SER---");
                                    }
                                                          
                                     
                                     if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                     cl++;
                                     amino_acidtxt.append("SER---");
                                    }
                                                           
                                                            if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                     cl++;
                                     amino_acidtxt.append("ARG---");
                                    }
                                                            
                                                             if (jTextArea1.getText().charAt(l)== 'A' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                     cl++;
                                     amino_acidtxt.append("ARG---");
                                    }
                                                             
                                                              if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'U')
                                    {
                                     cl++;
                                     amino_acidtxt.append("GLY---");
                                    }
                                                              
                                                               if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'C')
                                    {
                                     cl++;
                                     amino_acidtxt.append("GLY---");
                                    }
                                                               
                                                                if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'A')
                                    {
                                     cl++;
                                     amino_acidtxt.append("GLY---");
                                    }
                                                                
                                                                 if (jTextArea1.getText().charAt(l)== 'G' && jTextArea1.getText().charAt(m)== 'G'&& jTextArea1.getText().charAt(n)== 'G')
                                    {
                                        cl++;
                                        amino_acidtxt.append("GLY---");
                                    }
                                                                 
                                                                
                        }
                            
                        }
            
        }
        
          
         
        }
        catch(StringIndexOutOfBoundsException e)
        {
            
            
            System.out.println(" ");
        }
        
        catch(Exception a)
        {
            
        }
                    
        
        
    }//GEN-LAST:event_fasta1ActionPerformed

 
    private void fastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastaActionPerformed
        // TODO add your handling code here:
        
        
        try
        {
              int i;
            nuleotidetxt.append("NUCLEOTIDE\n\n");
      
              for (i = 0; i < 1000 ;i++)
                {             
                
                //    nuleotidetxt.append(jTextArea3.getText().substring(i));

                    if (jTextArea3.getText().charAt(i) == 'M') 
                    {
                      nuleotidetxt.append("AUG");
                    }
                    
                    if (jTextArea3.getText().charAt(i) == 'F') 
                    {
                      nuleotidetxt.append("UUU");
                    }
                    
                    if (jTextArea3.getText().charAt(i) == 'L') 
                    {
                      nuleotidetxt.append("UUA");
                    }
                    
                    if (jTextArea3.getText().charAt(i) == 'I') 
                    {
                      nuleotidetxt.append("AUU");
                    }
                    
                    
                     if (jTextArea3.getText().charAt(i) == 'S') 
                    {
                      nuleotidetxt.append("UCU");
                    }
                    
                      if (jTextArea3.getText().charAt(i) == 'p'|| jTextArea3.getText().charAt(i) == 'P') 
                    {
                      nuleotidetxt.append("CCA");
                    }
                      
                     if (jTextArea3.getText().charAt(i) == 'T') 
                    {
                      nuleotidetxt.append("ACU");
                    }
                     
                     if (jTextArea3.getText().charAt(i) == 'A') 
                    {
                      nuleotidetxt.append("GCU");
                    }
                     
                      if (jTextArea3.getText().charAt(i) == 'V') 
                    {
                      nuleotidetxt.append("GUU");
                    }
                       if (jTextArea3.getText().charAt(i) == 'Y') 
                    {
                      nuleotidetxt.append("UAU");
                    }
                       
                        if (jTextArea3.getText().charAt(i) == 'Q') 
                    {
                      nuleotidetxt.append("CAU");
                    }
                        
                     
                        
                           if (jTextArea3.getText().charAt(i) == 'K') 
                    {
                      nuleotidetxt.append("AAA");
                    }
                           
                              if (jTextArea3.getText().charAt(i) == 'D') 
                    {
                      nuleotidetxt.append("GAU");
                    }
                              
                                 if (jTextArea3.getText().charAt(i) == 'E') 
                    {
                      nuleotidetxt.append("GAG");
                    }
                                 
                                if (jTextArea3.getText().charAt(i) == 'C') 
                    {
                      nuleotidetxt.append("UGU");
                    }
                                
                                   if (jTextArea3.getText().charAt(i) == 'T') 
                    {
                      nuleotidetxt.append("UGG");
                    }
                                   
                                      if (jTextArea3.getText().charAt(i) == 'N') 
                    {
                      nuleotidetxt.append("GCG");
                    }
                                      
                                         if (jTextArea3.getText().charAt(i) == 'G') 
                    {
                      nuleotidetxt.append("GGU");
                    }
                           
                       
           
                }   
            
        }
        catch (StringIndexOutOfBoundsException e)
        {
       
            System.out.println("");
        }
        
              
              

    }//GEN-LAST:event_fastaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        jTextArea3.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
       
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if (jComboBox1.getSelectedItem().equals("Amino Acid"))
        {
            
            if (jTextField1.getText().equals("STOP") )
            {
              jLaltxt.setText(" UAA   UAG   UGA");
            }
            if (jTextField1.getText().equals("M") ||jTextField1.getText().equals("Meth") )
            {
                jLaltxt.setText("AUG");
            }
            
            if (jTextField1.getText().equals("F") ||jTextField1.getText().equals("Phe") )
            {
                jLaltxt.setText("UUU  UUC");
            }
            
            if (jTextField1.getText().equals("L") ||jTextField1.getText().equals("Leu") )
            {
                jLaltxt.setText("UUA  UUG  CUU  CUC  CUA  CUG");
            }
            
            if (jTextField1.getText().equals("I") ||jTextField1.getText().equals("IsoLeu") )
            {
                jLaltxt.setText("AUU  AUC  AUA");
            }
            
            if (jTextField1.getText().equals("V") ||jTextField1.getText().equals("Val") )
            {
                jLaltxt.setText("GUU  GUA  GUC  GUG");
            }
            
            if (jTextField1.getText().equals("S") ||jTextField1.getText().equals("Ser") )
            {
                jLaltxt.setText("UCU UCC UCA UCG AGU AGC ");
            }
            
            if (jTextField1.getText().equals("P") ||jTextField1.getText().equals("Pro") )
            {
                jLaltxt.setText("CCU CCC CCG CCA");
            }
            
            if (jTextField1.getText().equals("T") ||jTextField1.getText().equals("Thr") )
            {
                jLaltxt.setText("ACC ACU ACG ACA");
            }
            
            if (jTextField1.getText().equals("A") ||jTextField1.getText().equals("Ala") )
            {
                jLaltxt.setText("GCU GCC GCA GCG");
            }
            
            if (jTextField1.getText().equals("Y") ||jTextField1.getText().equals("Tyr") )
            {
                jLaltxt.setText("UAU UAC");
            }
            
            if (jTextField1.getText().equals("H") ||jTextField1.getText().equals("His") )
            {
                jLaltxt.setText("CAC CAU");
            }
            
            if (jTextField1.getText().equals("Q") ||jTextField1.getText().equals("Gln") )
            {
                jLaltxt.setText("CAA  CAG");
            }
            
            if (jTextField1.getText().equals("N") ||jTextField1.getText().equals("Asn") )
            {
                jLaltxt.setText("AAU  AAC");
            }
            
            if (jTextField1.getText().equals("K") ||jTextField1.getText().equals("Lys") )
            {
                jLaltxt.setText("AAA  AAG");
            }
            
            if (jTextField1.getText().equals("D") ||jTextField1.getText().equals("Asp") )
            {
                jLaltxt.setText("GAU  GAC");
            }
            
            if (jTextField1.getText().equals("E") ||jTextField1.getText().equals("Glu") )
            {
                jLaltxt.setText("GAA GAG");
            }
            
            if (jTextField1.getText().equals("C") ||jTextField1.getText().equals("Cys") )
            {
                jLaltxt.setText("UGU  UGC");
            }
            
            if (jTextField1.getText().equals("W") ||jTextField1.getText().equals("Trp") )
            {
                jLaltxt.setText("UGG");
            }
            
            if (jTextField1.getText().equals("R") ||jTextField1.getText().equals("Arg") )
            {
                jLaltxt.setText("CGU CGC CGA CGG AGA AGG ");
            }
            
            if (jTextField1.getText().equals("G") ||jTextField1.getText().equals("Gly") )
            {
                jLaltxt.setText("GGU GGC GGA GGG");
            }
            
            if (jTextField1.getText().equals("Z") || jTextField1.getText().equals("X") || jTextField1.getText().equals("B") || jTextField1.getText().equals("J") || jTextField1.getText().equals("U") || jTextField1.getText().equals("O"))   
            {
               JOptionPane.showMessageDialog(frame, "ENTER THE CORRECT CODE");
            }
        }
         
                  if (jComboBox1.getSelectedItem().equals("Nucleotide"))
                  {
                   
              if (jTextField1.getText().equals("UUU") || jTextField1.getText().equals("UUC") )
            {
                jLaltxt.setText("PHENYL ALANINE");
            } 
                   
                      if (jTextField1.getText().equals("UUA") || jTextField1.getText().equals("UUG") || jTextField1.getText().equals("CUC") || jTextField1.getText().equals("CUU") || jTextField1.getText().equals("CUA") || jTextField1.getText().equals("CUG"))
                      {
                        jLaltxt.setText("LEUCINE");
                      }
                      
                      if (jTextField1.getText().equals("AUU") || jTextField1.getText().equals("AUC") || jTextField1.getText().equals("AUA")) 
                      {
                        jLaltxt.setText("ISO LEUCINE");
                      }
                      
                      if (jTextField1.getText().equals("AUG"))
                      {
                        jLaltxt.setText("METHIONINE");
                      }
                      
                      if (jTextField1.getText().equals("GUU") || jTextField1.getText().equals("GUC") || jTextField1.getText().equals("GUA") || jTextField1.getText().equals("GUG")) 
                      {
                         jLaltxt.setText("VALINE");
                      }
                      
                      if (jTextField1.getText().equals("UCU") || jTextField1.getText().equals("UCC") || jTextField1.getText().equals("UCA") || jTextField1.getText().equals("UCG") || jTextField1.getText().equals("AGU") || jTextField1.getText().equals("AGC")) 
                      {
                          jLaltxt.setText("SERINE");
                          
                      }
                      
                      if (jTextField1.getText().equals("CCU") || jTextField1.getText().equals("CCC") || jTextField1.getText().equals("CCA") || jTextField1.getText().equals("CCG"))
                      {
                       jLaltxt.setText("PROLINE");
                      }
                      
                      if (jTextField1.getText().equals("ACU") || jTextField1.getText().equals("ACC") || jTextField1.getText().equals("ACA") || jTextField1.getText().equals("ACG")) 
                      {
                       jLaltxt.setText("THREONINE");
                      }
                      
                      if (jTextField1.getText().equals("GCU") || jTextField1.getText().equals("GCC") || jTextField1.getText().equals("GCA") || jTextField1.getText().equals("GCG")) 
                      {
                       jLaltxt.setText("ALANINE");
                      }
                      
                      if (jTextField1.getText().equals("UAU") || jTextField1.getText().equals("UAC"))
                      {
                        jLaltxt.setText("TYROSINE");
                      }
                      
                      if (jTextField1.getText().equals("UAA") || jTextField1.getText().equals("UAG") || jTextField1.getText().equals("UGA"))
                      {
                      jLaltxt.setText("STOP CODON");
                      }
                      
                      if (jTextField1.getText().equals("CAU") || jTextField1.getText().equals("CAC"))
                      {
                       jLaltxt.setText("HISTIDINE");
                      }
                      
                      if (jTextField1.getText().equals("CAA") || jTextField1.getText().equals("CAG"))
                      {
                      jLaltxt.setText("GLUTAMINE");
                      }
                      
                      if (jTextField1.getText().equals("AAU") || jTextField1.getText().equals("AAC"))
                      {
                      jLaltxt.setText("ASPARAGINE");
                      }
                      
                      if (jTextField1.getText().equals("AAA") || jTextField1.getText().equals("AGG"))
                      {
                      jLaltxt.setText("LYSINE");
                      }
                      
                      if (jTextField1.getText().equals("GAU") || jTextField1.getText().equals("GAC"))
                      {
                       jLaltxt.setText("ASPARATE");
                      }
                      
                      if (jTextField1.getText().equals("GAA") || jTextField1.getText().equals("GAG"))
                      {
                      jLaltxt.setText("GLUTAMATE");
                      }
                      
                      if (jTextField1.getText().equals("UGG"))
                      {
                       jLaltxt.setText("TRYPTOPHAN");
                      }
                      
                      if (jTextField1.getText().equals("CGU") || jTextField1.getText().equals("CGC") || jTextField1.getText().equals("CGA") || jTextField1.getText().equals("CGG"))
                      {
                       jLaltxt.setText("ARAGININE");
                      }
                      
                      if (jTextField1.getText().equals("GGC") || jTextField1.getText().equals("GGU") || jTextField1.getText().equals("GGA") || jTextField1.getText().equals("GGG") )
                      {
                       jLaltxt.setText("GLYCINE");
                      }
    
                  }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        jLaltxt.setText(null);
        jTextField1.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        amino_acidtxt.setText(null);
        nuleotidetxt.setText(null);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fasta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea amino_acidtxt;
    private javax.swing.JButton fasta;
    private javax.swing.JButton fasta1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLaltxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea nuleotidetxt;
    // End of variables declaration//GEN-END:variables
}
